description: Notes de cours
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
show_downloads: false
theme: jekyll-theme-tactile
title: 420-174-ST A2019 (Suppléments technologiques)
